export const SIGNED_UP_USER_LOGIN_REQUEST = 'SIGNED_UP_USER_LOGIN_REQUEST'
export const SIGNED_UP_USER_LOGIN_SUCCESS = 'SIGNED_UP_USER_LOGIN_SUCCESS'
export const SIGNED_UP_USER_LOGIN_FAIL= 'SIGNED_UP_USER_LOGIN_FAIL'
export const SIGNED_UP_USER_LOGOUT = 'SIGNED_UP_USER_LOGOUT'

export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";