POST http://localhost:8080/app/signup/2/business
Content-Type: application/json

{
    "businessName": "Marya",
    "accountHolderName": "Ibrahim",
    "email": "abdu6@hello.co",
    "phoneNumber": "12345",
    "password": "qwerty"
}