POST http://localhost:8080/app/signup/2/individual
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Ibrahim",
    "email": "john@hello.com",
    "phoneNumber": "123456",
    "password": "qwerty"

}