POST http://localhost:8080/app/store/createStore
Content-Type: application/json

{
    "storeName": "Lulu",
    "tagLine":"Big Blllrd",
    "description":"We put the B in Beautiful",
    "link":"lulu.gaged.io",
    "logo":"https://www.freepik.com/free-photo/blue-concrete-wall-textures-background_4202473.htm#page=1&query=blue%20background&position=3&from_view=keyword"
}