POST http://localhost:8080/app/signup/2/individual
Content-Type: application/json

{
    "firstName": "Uniquer",
    "lastName": "Ibrahim",
    "email": "abdulw@hellog.com",
    "phoneNumber": "12345",
    "password": "qwerty"

}