export const SIGNED_UP_BUSINESS_LOGIN_REQUEST =
  "SIGNED_UP_BUSINESS_LOGIN_REQUEST";
export const SIGNED_UP_BUSINESS_LOGIN_SUCCESS =
  "SIGNED_UP_BUSINESS_LOGIN_SUCCESS";
export const SIGNED_UP_BUSINESS_LOGIN_FAIL = "SIGNED_UP_BUSINESS_LOGIN_FAIL";
export const SIGNED_UP_BUSINESS_LOGOUT = "SIGNED_UP_BUSINESS_LOGOUT";

export const BUSINESS_SIGN_UP_REQUEST = "BUSINESS_SIGN_UP_REQUEST";
export const BUSINESS_SIGN_UP_SUCCESS = "BUSINESS_SIGN_UP_SUCCESS";
export const BUSINESS_SIGN_UP_FAIL = "BUSINESS_SIGN_UP_FAIL";

export const LOAD_BUSINESS_REQUEST = "LOAD_BUSINESS_REQUEST";
export const LOAD_BUSINESS_SUCCESS = "LOAD_BUSINESS_SUCCESS";
export const LOAD_BUSINESS_FAIL = "LOAD_BUSINESS_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_BUSINESS_PROFILE_REQUEST =
  "UPDATE_BUSINESS_PROFILE_REQUEST";
export const UPDATE_BUSINESS_PROFILE_SUCCESS =
  "UPDATE_BUSINESS_PROFILE_SUCCESS";
export const UPDATE_BUSINESS_PROFILE_RESET = "UPDATE_BUSINESS_PROFILE_RESET";
export const UPDATE_BUSINESS_PROFILE_FAIL = "UPDATE_BUSINESS_PROFILE_FAIL";

export const UPDATE_BUSINESS_PASSWORD_REQUEST =
  "UPDATE_BUSINESS_PASSWORD_REQUEST";
export const UPDATE_BUSINESS_PASSWORD_SUCCESS =
  "UPDATE_BUSINESS_PASSWORD_SUCCESS";
export const UPDATE_BUSINESS_PASSWORD_RESET = "UPDATE_BUSINESS_PASSWORD_RESET";
export const UPDATE_BUSINESS_PASSWORD_FAIL = "UPDATE_BUSINESS_PASSWORD_FAIL";

export const FORGOT_BUSINESS_PASSWORD_REQUEST =
  "FORGOT_BUSINESS_PASSWORD_REQUEST";
export const FORGOT_BUSINESS_PASSWORD_SUCCESS =
  "FORGOT_BUSINESS_PASSWORD_SUCCESS";
export const FORGOT_BUSINESS_PASSWORD_FAIL = "FORGOT_BUSINESS_PASSWORD_FAIL";

export const RESET_BUSINESS_PASSWORD_REQUEST =
  "RESET_BUSINESS_PASSWORD_REQUEST";
export const RESET_BUSINESS_PASSWORD_SUCCESS =
  "RESET_BUSINESS_PASSWORD_SUCCESS";
export const RESET_BUSINESS_PASSWORD_FAIL = "RESET_BUSINESS_PASSWORD_FAIL";

export const ALL_BUSINESSS_REQUEST = "ALL_BUSINESSS_REQUEST";
export const ALL_BUSINESSS_SUCCESS = "ALL_BUSINESSS_SUCCESS";
export const ALL_BUSINESSS_FAIL = "ALL_BUSINESSS_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";

export const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_RESET = "UPDATE_BUSINESS_RESET";
export const UPDATE_BUSINESS_FAIL = "UPDATE_BUSINESS_FAIL";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAIL = "DELETE_BUSINESS_FAIL";
export const DELETE_BUSINESS_RESET = "DELETE_BUSINESS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
