export const SIGNED_UP_BUSINESS_LOGIN_REQUEST =
  "SIGNED_UP_BUSINESS_LOGIN_REQUEST";
export const SIGNED_UP_BUSINESS_LOGIN_SUCCESS =
  "SIGNED_UP_BUSINESS_LOGIN_SUCCESS";
export const SIGNED_UP_BUSINESS_LOGIN_FAIL = "SIGNED_UP_BUSINESS_LOGIN_FAIL";
export const SIGNED_UP_BUSINESS_LOGOUT = "SIGNED_UP_BUSINESS_LOGOUT";

export const BUSINESS_SIGN_UP_REQUEST = "BUSINESS_SIGN_UP_REQUEST";
export const BUSINESS_SIGN_UP_SUCCESS = "BUSINESS_SIGN_UP_SUCCESS";
export const BUSINESS_SIGN_UP_FAIL = "BUSINESS_SIGN_UP_FAIL";

export const LOAD_BUSINESS_REQUEST = "LOAD_BUSINESS_REQUEST";
export const LOAD_BUSINESS_SUCCESS = "LOAD_BUSINESS_SUCCESS";
export const LOAD_BUSINESS_FAIL = "LOAD_BUSINESS_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_BUSINESS_PROFILE_REQUEST =
  "UPDATE_BUSINESS_PROFILE_REQUEST";
export const UPDATE_BUSINESS_PROFILE_SUCCESS =
  "UPDATE_BUSINESS_PROFILE_SUCCESS";
export const UPDATE_BUSINESS_PROFILE_RESET = "UPDATE_BUSINESS_PROFILE_RESET";
export const UPDATE_BUSINESS_PROFILE_FAIL = "UPDATE_BUSINESS_PROFILE_FAIL";

export const UPDATE_BUSINESS_PASSWORD_REQUEST =
  "UPDATE_BUSINESS_PASSWORD_REQUEST";
export const UPDATE_BUSINESS_PASSWORD_SUCCESS =
  "UPDATE_BUSINESS_PASSWORD_SUCCESS";
export const UPDATE_BUSINESS_PASSWORD_RESET = "UPDATE_BUSINESS_PASSWORD_RESET";
export const UPDATE_BUSINESS_PASSWORD_FAIL = "UPDATE_BUSINESS_PASSWORD_FAIL";

export const FORGOT_BUSINESS_PASSWORD_REQUEST =
  "FORGOT_BUSINESS_PASSWORD_REQUEST";
export const FORGOT_BUSINESS_PASSWORD_SUCCESS =
  "FORGOT_BUSINESS_PASSWORD_SUCCESS";
export const FORGOT_BUSINESS_PASSWORD_FAIL = "FORGOT_BUSINESS_PASSWORD_FAIL";

export const RESET_BUSINESS_PASSWORD_REQUEST =
  "RESET_BUSINESS_PASSWORD_REQUEST";
export const RESET_BUSINESS_PASSWORD_SUCCESS =
  "RESET_BUSINESS_PASSWORD_SUCCESS";
export const RESET_BUSINESS_PASSWORD_FAIL = "RESET_BUSINESS_PASSWORD_FAIL";

export const ALL_BUSINESSS_REQUEST = "ALL_BUSINESSS_REQUEST";
export const ALL_BUSINESSS_SUCCESS = "ALL_BUSINESSS_SUCCESS";
export const ALL_BUSINESSS_FAIL = "ALL_BUSINESSS_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";

export const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_RESET = "UPDATE_BUSINESS_RESET";
export const UPDATE_BUSINESS_FAIL = "UPDATE_BUSINESS_FAIL";

export const DELETE_BUSINESS_REQUEST = "DELETE_BUSINESS_REQUEST";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_FAIL = "DELETE_BUSINESS_FAIL";
export const DELETE_BUSINESS_RESET = "DELETE_BUSINESS_RESET";

export const NEW_BUSINESS_ORDERED_FROM_REQUEST =
  "NEW_BUSINESS_ORDERED_FROM_REQUEST";
export const NEW_BUSINESS_ORDERED_FROM_SUCCESS =
  "NEW_BUSINESS_ORDERED_FROM_SUCCESS";
export const NEW_BUSINESS_ORDERED_FROM_RESET =
  "NEW_BUSINESS_ORDERED_FROM_RESET";
export const NEW_BUSINESS_ORDERED_FROM_FAIL = "NEW_BUSINESS_ORDERED_FROM_FAIL";

export const ALL_BUSINESS_ORDERED_FROM_REQUEST =
  "ALL_BUSINESS_ORDERED_FROM_REQUEST";
export const ALL_BUSINESS_ORDERED_FROM_SUCCESS =
  "ALL_BUSINESS_ORDERED_FROM_SUCCESS";
export const ALL_BUSINESS_ORDERED_FROM_FAIL = "ALL_BUSINESS_ORDERED_FROM_FAIL";

export const DELETE_BUSINESS_ORDERED_FROM_REQUEST =
  "DELETE_BUSINESS_ORDERED_FROM_REQUEST";
export const DELETE_BUSINESS_ORDERED_FROM_SUCCESS =
  "DELETE_BUSINESS_ORDERED_FROM_SUCCESS";
export const DELETE_BUSINESS_ORDERED_FROM_RESET =
  "DELETE_BUSINESS_ORDERED_FROM_RESET";
export const DELETE_BUSINESS_ORDERED_FROM_FAIL =
  "DELETE_BUSINESS_ORDERED_FROM_FAIL";

export const NEW_CAMPAIGN_INVESTED_REQUEST = "NEW_CAMPAIGN_INVESTED_REQUEST";
export const NEW_CAMPAIGN_INVESTED_SUCCESS = "NEW_CAMPAIGN_INVESTED_SUCCESS";
export const NEW_CAMPAIGN_INVESTED_RESET = "NEW_CAMPAIGN_INVESTED_RESET";
export const NEW_CAMPAIGN_INVESTED_FAIL = "NEW_CAMPAIGN_INVESTED_FAIL";

export const NEW_CAMPAIGN_PAYOUT_REQUEST = "NEW_CAMPAIGN_PAYOUT_REQUEST";
export const NEW_CAMPAIGN_PAYOUT_SUCCESS = "NEW_CAMPAIGN_PAYOUT_SUCCESS";
export const NEW_CAMPAIGN_PAYOUT_RESET = "NEW_CAMPAIGN_PAYOUT_RESET";
export const NEW_CAMPAIGN_PAYOUT_FAIL = "NEW_CAMPAIGN_PAYOUT_FAIL";

export const ALL_CAMPAIGNS_INVESTED_REQUEST = "ALL_CAMPAIGNS_INVESTED_REQUEST";
export const ALL_CAMPAIGNS_INVESTED_SUCCESS = "ALL_CAMPAIGNS_INVESTED_SUCCESS";
export const ALL_CAMPAIGNS_INVESTED_FAIL = "ALL_CAMPAIGNS_INVESTED_FAIL";

export const ALL_CAMPAIGNS_PAYOUT_REQUEST = "ALL_CAMPAIGNS_PAYOUT_REQUEST";
export const ALL_CAMPAIGNS_PAYOUT_SUCCESS = "ALL_CAMPAIGNS_PAYOUT_SUCCESS";
export const ALL_CAMPAIGNS_PAYOUT_FAIL = "ALL_CAMPAIGNS_PAYOUT_FAIL";

export const PARTICULAR_CAMPAIGNS_INVESTED_REQUEST = "PARTICULAR_CAMPAIGNS_INVESTED_REQUEST";
export const PARTICULAR_CAMPAIGNS_INVESTED_SUCCESS = "PARTICULAR_CAMPAIGNS_INVESTED_SUCCESS";
export const PARTICULAR_CAMPAIGNS_INVESTED_FAIL = "PARTICULAR_CAMPAIGNS_INVESTED_FAIL";
export const PARTICULAR_CAMPAIGNS_PAYOUT_REQUEST = "PARTICULAR_CAMPAIGNS_PAYOUT_REQUEST";
export const PARTICULAR_CAMPAIGNS_PAYOUT_SUCCESS = "PARTICULAR_CAMPAIGNS_PAYOUT_SUCCESS";
export const PARTICULAR_CAMPAIGNS_PAYOUT_FAIL = "PARTICULAR_CAMPAIGNS_PAYOUT_FAIL";


export const DELETE_CAMPAIGN_INVESTED_REQUEST =
  "DELETE_CAMPAIGN_INVESTED_REQUEST";
export const DELETE_CAMPAIGN_INVESTED_SUCCESS =
  "DELETE_CAMPAIGN_INVESTED_SUCCESS";
export const DELETE_CAMPAIGN_INVESTED_RESET = "DELETE_CAMPAIGN_INVESTED_RESET";
export const DELETE_CAMPAIGN_INVESTED_FAIL = "DELETE_CAMPAIGN_INVESTED_FAIL";

export const DELETE_CAMPAIGN_PAYOUT_REQUEST =
  "DELETE_CAMPAIGN_PAYOUT_REQUEST";
export const DELETE_CAMPAIGN_PAYOUT_SUCCESS =
  "DELETE_CAMPAIGN_PAYOUT_SUCCESS";
export const DELETE_CAMPAIGN_PAYOUT_RESET = "DELETE_CAMPAIGN_PAYOUT_RESET";
export const DELETE_CAMPAIGN_PAYOUT_FAIL = "DELETE_CAMPAIGN_PAYOUT_FAIL";

export const NEW_CAMPAIGN_REVIEWS_REQUEST = "NEW_CAMPAIGN_REVIEWS_REQUEST";
export const NEW_CAMPAIGN_REVIEWS_SUCCESS = "NEW_CAMPAIGN_REVIEWS_SUCCESS";
export const NEW_CAMPAIGN_REVIEWS_RESET = "NEW_CAMPAIGN_REVIEWS_RESET";
export const NEW_CAMPAIGN_REVIEWS_FAIL = "NEW_CAMPAIGN_REVIEWS_FAIL";

export const ALL_CAMPAIGNS_REVIEWS_REQUEST = "ALL_CAMPAIGNS_REVIEWS_REQUEST";
export const ALL_CAMPAIGNS_REVIEWS_SUCCESS = "ALL_CAMPAIGNS_REVIEWS_SUCCESS";
export const ALL_CAMPAIGNS_REVIEWS_FAIL = "ALL_CAMPAIGNS_REVIEWS_FAIL";

export const DELETE_CAMPAIGN_REVIEWS_REQUEST =
  "DELETE_CAMPAIGN_REVIEWS_REQUEST";
export const DELETE_CAMPAIGN_REVIEWS_SUCCESS =
  "DELETE_CAMPAIGN_REVIEWS_SUCCESS";
export const DELETE_CAMPAIGN_REVIEWS_RESET = "DELETE_CAMPAIGN_REVIEWS_RESET";
export const DELETE_CAMPAIGN_REVIEWS_FAIL = "DELETE_CAMPAIGN_REVIEWS_FAIL";

export const NEW_PRODUCT_REVIEWS_REQUEST = "NEW_PRODUCT_REVIEWS_REQUEST";
export const NEW_PRODUCT_REVIEWS_SUCCESS = "NEW_PRODUCT_REVIEWS_SUCCESS";
export const NEW_PRODUCT_REVIEWS_RESET = "NEW_PRODUCT_REVIEWS_RESET";
export const NEW_PRODUCT_REVIEWS_FAIL = "NEW_PRODUCT_REVIEWS_FAIL";

export const ALL_PRODUCTS_REVIEWS_REQUEST = "ALL_PRODUCTS_REVIEWS_REQUEST";
export const ALL_PRODUCTS_REVIEWS_SUCCESS = "ALL_PRODUCTS_REVIEWS_SUCCESS";
export const ALL_PRODUCTS_REVIEWS_FAIL = "ALL_PRODUCTS_REVIEWS_FAIL";

export const DELETE_PRODUCT_REVIEWS_REQUEST = "DELETE_PRODUCT_REVIEWS_REQUEST";
export const DELETE_PRODUCT_REVIEWS_SUCCESS = "DELETE_PRODUCT_REVIEWS_SUCCESS";
export const DELETE_PRODUCT_REVIEWS_RESET = "DELETE_PRODUCT_REVIEWS_RESET";
export const DELETE_PRODUCT_REVIEWS_FAIL = "DELETE_PRODUCT_REVIEWS_FAIL";

export const NEW_STORE_PRODUCT_REQUEST = "NEW_STORE_PRODUCT_REQUEST";
export const NEW_STORE_PRODUCT_SUCCESS = "NEW_STORE_PRODUCT_SUCCESS";
export const NEW_STORE_PRODUCT_RESET = "NEW_STORE_PRODUCT_RESET";
export const NEW_STORE_PRODUCT_FAIL = "NEW_STORE_PRODUCT_FAIL";

export const ALL_STORE_PRODUCTS_REQUEST = "ALL_STORE_PRODUCTS_REQUEST";
export const ALL_STORE_PRODUCTS_SUCCESS = "ALL_STORE_PRODUCTS_SUCCESS";
export const ALL_STORE_PRODUCTS_FAIL = "ALL_STORE_PRODUCTS_FAIL";

export const DELETE_STORE_PRODUCT_REQUEST = "DELETE_STORE_PRODUCT_REQUEST";
export const DELETE_STORE_PRODUCT_SUCCESS = "DELETE_STORE_PRODUCT_SUCCESS";
export const DELETE_STORE_PRODUCT_RESET = "DELETE_STORE_PRODUCT_RESET";
export const DELETE_STORE_PRODUCT_FAIL = "DELETE_STORE_PRODUCT_FAIL";

export const NEW_CAMPAIGN_STARTED_REQUEST = "NEW_CAMPAIGN_STARTED_REQUEST";
export const NEW_CAMPAIGN_STARTED_SUCCESS = "NEW_CAMPAIGN_STARTED_SUCCESS";
export const NEW_CAMPAIGN_STARTED_RESET = "NEW_CAMPAIGN_STARTED_RESET";
export const NEW_CAMPAIGN_STARTED_FAIL = "NEW_CAMPAIGN_STARTED_FAIL";

export const ALL_CAMPAIGNS_STARTED_REQUEST = "ALL_CAMPAIGNS_STARTED_REQUEST";
export const ALL_CAMPAIGNS_STARTED_SUCCESS = "ALL_CAMPAIGNS_STARTED_SUCCESS";
export const ALL_CAMPAIGNS_STARTED_FAIL = "ALL_CAMPAIGNS_STARTED_FAIL";

export const DELETE_CAMPAIGN_STARTED_REQUEST =
  "DELETE_CAMPAIGN_STARTED_REQUEST";
export const DELETE_CAMPAIGN_STARTED_SUCCESS =
  "DELETE_CAMPAIGN_STARTED_SUCCESS";
export const DELETE_CAMPAIGN_STARTED_RESET = "DELETE_CAMPAIGN_STARTED_RESET";
export const DELETE_CAMPAIGN_STARTED_FAIL = "DELETE_CAMPAIGN_STARTED_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
