export const SIGNED_UP_BUSINESS_LOGIN_REQUEST = 'SIGNED_UP_BUSINESS_LOGIN_REQUEST'
export const SIGNED_UP_BUSINESS_LOGIN_SUCCESS = 'SIGNED_UP_BUSINESS_LOGIN_SUCCESS'
export const SIGNED_UP_BUSINESS_LOGIN_FAIL= 'SIGNED_UP_BUSINESS_LOGIN_FAIL'
export const SIGNED_UP_BUSINESS_LOGOUT = 'SIGNED_UP_BUSINESS_LOGOUT'


export const BUSINESS_SIGN_UP_REQUEST = "BUSINESS_SIGN_UP_REQUEST";
export const BUSINESS_SIGN_UP_SUCCESS = "BUSINESS_SIGN_UP_SUCCESS";
export const BUSINESS_SIGN_UP_FAIL = "BUSINESS_SIGN_UP_FAIL";