export const CREATE_BUSINESS_ORDER_REQUEST = "CREATE_BUSINESS_ORDER_REQUEST";
export const CREATE_BUSINESS_ORDER_SUCCESS = "CREATE_BUSINESS_ORDER_SUCCESS";
export const CREATE_BUSINESS_ORDER_FAIL = "CREATE_BUSINESS_ORDER_FAIL";

export const MY_BUSINESS_ORDERS_REQUEST = "MY_BUSINESS_ORDERS_REQUEST";
export const MY_BUSINESS_ORDERS_SUCCESS = "MY_BUSINESS_ORDERS_SUCCESS";
export const MY_BUSINESS_ORDERS_FAIL = "MY_BUSINESS_ORDERS_FAIL";

export const ALL_BUSINESS_ORDERS_REQUEST = "ALL_BUSINESS_ORDERS_REQUEST";
export const ALL_BUSINESS_ORDERS_SUCCESS = "ALL_BUSINESS_ORDERS_SUCCESS";
export const ALL_BUSINESS_ORDERS_FAIL = "ALL_BUSINESS_ORDERS_FAIL";

export const UPDATE_BUSINESS_ORDER_REQUEST = "UPDATE_BUSINESS_ORDER_REQUEST";
export const UPDATE_BUSINESS_ORDER_SUCCESS = "UPDATE_BUSINESS_ORDER_SUCCESS";
export const UPDATE_BUSINESS_ORDER_RESET = "UPDATE_BUSINESS_ORDER_RESET";
export const UPDATE_BUSINESS_ORDER_FAIL = "UPDATE_BUSINESS_ORDER_FAIL";

export const DELETE_BUSINESS_ORDER_REQUEST = "DELETE_BUSINESS_ORDER_REQUEST";
export const DELETE_BUSINESS_ORDER_SUCCESS = "DELETE_BUSINESS_ORDER_SUCCESS";
export const DELETE_BUSINESS_ORDER_RESET = "DELETE_BUSINESS_ORDER_RESET";
export const DELETE_BUSINESS_ORDER_FAIL = "DELETE_BUSINESS_ORDER_FAIL";

export const BUSINESS_ORDER_DETAILS_REQUEST = "BUSINESS_ORDER_DETAILS_REQUEST";
export const BUSINESS_ORDER_DETAILS_SUCCESS = "BUSINESS_ORDER_DETAILS_SUCCESS";
export const BUSINESS_ORDER_DETAILS_FAIL = "BUSINESS_ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
