export const ALL_CAMPAIGN_REQUEST = "ALL_CAMPAIGN_REQUEST";
export const ALL_CAMPAIGN_SUCCESS = "ALL_CAMPAIGN_SUCCESS";
export const ALL_CAMPAIGN_FAIL = "ALL_CAMPAIGN_FAIL";

export const ADMIN_CAMPAIGN_REQUEST = "ADMIN_CAMPAIGN_REQUEST";
export const ADMIN_CAMPAIGN_SUCCESS = "ADMIN_CAMPAIGN_SUCCESS";
export const ADMIN_CAMPAIGN_FAIL = "ADMIN_CAMPAIGN_FAIL";

export const NEW_CAMPAIGN_REQUEST = "NEW_CAMPAIGN_REQUEST";
export const NEW_CAMPAIGN_SUCCESS = "NEW_CAMPAIGN_SUCCESS";
export const NEW_CAMPAIGN_RESET = "NEW_CAMPAIGN_RESET";
export const NEW_CAMPAIGN_FAIL = "NEW_CAMPAIGN_FAIL";

export const UPDATE_CAMPAIGN_REQUEST = "UPDATE_CAMPAIGN_REQUEST";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_RESET = "UPDATE_CAMPAIGN_RESET";
export const UPDATE_CAMPAIGN_FAIL = "UPDATE_CAMPAIGN_FAIL";

export const DELETE_CAMPAIGN_REQUEST = "DELETE_CAMPAIGN_REQUEST";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_RESET = "DELETE_CAMPAIGN_RESET";
export const DELETE_CAMPAIGN_FAIL = "DELETE_CAMPAIGN_FAIL";

export const CAMPAIGN_DETAILS_REQUEST = "CAMPAIGN_DETAILS_REQUEST";
export const CAMPAIGN_DETAILS_SUCCESS = "CAMPAIGN_DETAILS_SUCCESS";
export const CAMPAIGN_DETAILS_FAIL = "CAMPAIGN_DETAILS_FAIL";

export const NEW_INDIVIDUAL_DONOR_REQUEST = "NEW_INDIVIDUAL_DONOR_REQUEST";
export const NEW_INDIVIDUAL_DONOR_SUCCESS = "NEW_INDIVIDUAL_DONOR_SUCCESS";
export const NEW_INDIVIDUAL_DONOR_RESET = "NEW_INDIVIDUAL_DONOR_RESET";
export const NEW_INDIVIDUAL_DONOR_FAIL = "NEW_INDIVIDUAL_DONOR_FAIL";

export const ALL_INDIVIDUAL_DONORS_REQUEST = "ALL_INDIVIDUAL_DONORS_REQUEST";
export const ALL_INDIVIDUAL_DONORS_SUCCESS = "ALL_INDIVIDUAL_DONORS_SUCCESS";
export const ALL_INDIVIDUAL_DONORS_FAIL = "ALL_INDIVIDUAL_DONORS_FAIL";

export const DELETE_INDIVIDUAL_DONOR_REQUEST =
  "DELETE_INDIVIDUAL_DONOR_REQUEST";
export const DELETE_INDIVIDUAL_DONOR_SUCCESS =
  "DELETE_INDIVIDUAL_DONOR_SUCCESS";
export const DELETE_INDIVIDUAL__DONOR_RESET = "DELETE_INDIVIDUAL_DONOR_RESET";
export const DELETE_INDIVIDUAL_DONOR_FAIL = "DELETE_INDIVIDUAL_DONOR_FAIL";

export const NEW_BUSINESS_DONOR_REQUEST = "NEW_BUSINESS_DONOR_REQUEST";
export const NEW_BUSINESS_DONOR_SUCCESS = "NEW_BUSINESS_DONOR_SUCCESS";
export const NEW_BUSINESS_DONOR_RESET = "NEW_BUSINESS_DONOR_RESET";
export const NEW_BUSINESS_DONOR_FAIL = "NEW_BUSINESS_DONOR_FAIL";

export const ALL_BUSINESS_DONORS_REQUEST = "ALL_BUSINESS_DONORS_REQUEST";
export const ALL_BUSINESS_DONORS_SUCCESS = "ALL_BUSINESS_DONORS_SUCCESS";
export const ALL_BUSINESS_DONORS_FAIL = "ALL_BUSINESS_DONORS_FAIL";

export const DELETE_BUSINESS_DONOR_REQUEST = "DELETE_BUSINESS_DONOR_REQUEST";
export const DELETE_BUSINESS_DONOR_SUCCESS = "DELETE_BUSINESS_DONOR_SUCCESS";
export const DELETE_BUSINESS__DONOR_RESET = "DELETE_BUSINESS_DONOR_RESET";
export const DELETE_BUSINESS_DONOR_FAIL = "DELETE_BUSINESS_DONOR_FAIL";

export const NEW_CAMPAIGN_BUSINESS_REVIEW_REQUEST =
  "NEW_CAMPAIGN_BUSINESS_REVIEW_REQUEST";
export const NEW_CAMPAIGN_BUSINESS_REVIEW_SUCCESS =
  "NEW_CAMPAIGN_BUSINESS_REVIEW_SUCCESS";
export const NEW_CAMPAIGN_BUSINESS_REVIEW_RESET =
  "NEW_CAMPAIGN_BUSINESS_REVIEW_RESET";
export const NEW_CAMPAIGN_BUSINESS_REVIEW_FAIL =
  "NEW_CAMPAIGN_BUSINESS_REVIEW_FAIL";

export const ALL_CAMPAIGN_BUSINESS_REVIEWS_REQUEST =
  "ALL_CAMPAIGN_BUSINESS_REVIEWS_REQUEST";
export const ALL_CAMPAIGN_BUSINESS_REVIEWS_SUCCESS =
  "ALL_CAMPAIGN_BUSINESS_REVIEWS_SUCCESS";
export const ALL_CAMPAIGN_BUSINESS_REVIEWS_FAIL =
  "ALL_CAMPAIGN_BUSINESS_REVIEWS_FAIL";

export const DELETE_CAMPAIGN_BUSINESS_REVIEW_REQUEST =
  "DELETE_CAMPAIGN_BUSINESS_REVIEW_REQUEST";
export const DELETE_CAMPAIGN_BUSINESS_REVIEW_SUCCESS =
  "DELETE_CAMPAIGN_BUSINESS_REVIEW_SUCCESS";
export const DELETE_CAMPAIGN_BUSINESS_REVIEW_RESET =
  "DELETE_CAMPAIGN_BUSINESS_REVIEW_RESET";
export const DELETE_CAMPAIGN_BUSINESS_REVIEW_FAIL =
  "DELETE_CAMPAIGN_BUSINESS_REVIEW_FAIL";

export const NEW_CAMPAIGN_INDIVIDUAL_REVIEW_REQUEST =
  "NEW_CAMPAIGN_INDIVIDUAL_REVIEW_REQUEST";
export const NEW_CAMPAIGN_INDIVIDUAL_REVIEW_SUCCESS =
  "NEW_CAMPAIGN_INDIVIDUAL_REVIEW_SUCCESS";
export const NEW_CAMPAIGN_INDIVIDUAL_REVIEW_RESET =
  "NEW_CAMPAIGN_INDIVIDUAL_REVIEW_RESET";
export const NEW_CAMPAIGN_INDIVIDUAL_REVIEW_FAIL =
  "NEW_CAMPAIGN_INDIVIDUAL_REVIEW_FAIL";

export const ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_REQUEST =
  "ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_REQUEST";
export const ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_SUCCESS =
  "ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_SUCCESS";
export const ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_FAIL =
  "ALL_CAMPAIGN_INDIVIDUAL_REVIEWS_FAIL";

export const DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_REQUEST =
  "DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_REQUEST";
export const DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_SUCCESS =
  "DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_SUCCESS";
export const DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_RESET =
  "DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_RESET";
export const DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_FAIL =
  "DELETE_CAMPAIGN_INDIVIDUAL_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
