export const CREATE_INDIVIDUAL_ORDER_REQUEST =
  "CREATE_INDIVIDUAL_ORDER_REQUEST";
export const CREATE_INDIVIDUAL_ORDER_SUCCESS =
  "CREATE_INDIVIDUAL_ORDER_SUCCESS";
export const CREATE_INDIVIDUAL_ORDER_FAIL = "CREATE_INDIVIDUAL_ORDER_FAIL";

export const MY_INDIVIDUAL_ORDERS_REQUEST = "MY_INDIVIDUAL_ORDERS_REQUEST";
export const MY_INDIVIDUAL_ORDERS_SUCCESS = "MY_INDIVIDUAL_ORDERS_SUCCESS";
export const MY_INDIVIDUAL_ORDERS_FAIL = "MY_INDIVIDUAL_ORDERS_FAIL";

export const ALL_INDIVIDUAL_ORDERS_REQUEST = "ALL_INDIVIDUAL_ORDERS_REQUEST";
export const ALL_INDIVIDUAL_ORDERS_SUCCESS = "ALL_INDIVIDUAL_ORDERS_SUCCESS";
export const ALL_INDIVIDUAL_ORDERS_FAIL = "ALL_INDIVIDUAL_ORDERS_FAIL";

export const UPDATE_INDIVIDUAL_ORDER_REQUEST =
  "UPDATE_INDIVIDUAL_ORDER_REQUEST";
export const UPDATE_INDIVIDUAL_ORDER_SUCCESS =
  "UPDATE_INDIVIDUAL_ORDER_SUCCESS";
export const UPDATE_INDIVIDUAL_ORDER_RESET = "UPDATE_INDIVIDUAL_ORDER_RESET";
export const UPDATE_INDIVIDUAL_ORDER_FAIL = "UPDATE_INDIVIDUAL_ORDER_FAIL";

export const DELETE_INDIVIDUAL_ORDER_REQUEST =
  "DELETE_INDIVIDUAL_ORDER_REQUEST";
export const DELETE_INDIVIDUAL_ORDER_SUCCESS =
  "DELETE_INDIVIDUAL_ORDER_SUCCESS";
export const DELETE_INDIVIDUAL_ORDER_RESET = "DELETE_INDIVIDUAL_ORDER_RESET";
export const DELETE_INDIVIDUAL_ORDER_FAIL = "DELETE_INDIVIDUAL_ORDER_FAIL";

export const INDIVIDUAL_ORDER_DETAILS_REQUEST =
  "INDIVIDUAL_ORDER_DETAILS_REQUEST";
export const INDIVIDUAL_ORDER_DETAILS_SUCCESS =
  "INDIVIDUAL_ORDER_DETAILS_SUCCESS";
export const INDIVIDUAL_ORDER_DETAILS_FAIL = "INDIVIDUAL_ORDER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
