export const STORE_PRODUCTS_LIST_REQUEST = "STORE_PRODUCTS_LIST_REQUEST";
export const STORE_PRODUCTS_LIST_SUCCESS = "STORE_PRODUCTS_LIST_SUCCESS";
export const STORE_PRODUCTS_LIST_FAIL = "STORE_PRODUCT_LISST_FAIL";

export const STORE_PRODUCTS_CREATE_REQUEST = "STORE_PRODUCTS_CREATE_REQUEST";
export const STORE_PRODUCTS_CREATE_SUCCESS = "STORE_PRODUCTS_CREATE_SUCCESS";
export const STORE_PRODUCTS_CREATE_FAIL = "STORE_PRODUCTS_CREATE_FAIL";

export const STORE_PRODUCTS_UPDATE_REQUEST = "STORE_PRODUCTS_UPDATE_REQUEST";
export const STORE_PRODUCTS_UPDATE_SUCCESS = "STORE_PRODUCTS_UPDATE_SUCCESS";
export const STORE_PRODUCTS_UPDATE_FAIL = "STORE_PRODUCTS_UPDATE_FAIL";

export const STORE_PRODUCTS_DELETE_REQUEST = "STORE_PRODUCTS_DELETE_REQUEST";
export const STORE_PRODUCTS_DELETE_SUCCESS = "STORE_PRODUCTS_DELETE_SUCCESS";
export const STORE_PRODUCTS_DELETE_FAIL = "STORE_PRODUCTS_DELETE_FAIL";
