export const STORE_PRODUCTS_LIST_REQUEST = "STORE_PRODUCTS_LIST_REQUEST";
export const STORE_PRODUCTS_LIST_SUCCESS = "STORE_PRODUCTS_LIST_SUCCESS";
export const STORE_PRODUCTS_LIST_FAIL = "STORE_PRODUCT_LISST_FAIL";

export const STORE_PRODUCTS_CREATE_REQUEST = "STORE_PRODUCTS_CREATE_REQUEST";
export const STORE_PRODUCTS_CREATE_SUCCESS = "STORE_PRODUCTS_CREATE_SUCCESS";
export const STORE_PRODUCTS_CREATE_FAIL = "STORE_PRODUCTS_CREATE_FAIL";
export const STORE_PRODUCTS_CREATE_RESET = "STORE_PRODUCTS_CREATE_RESET";

export const STORE_PRODUCTS_UPDATE_REQUEST = "STORE_PRODUCTS_UPDATE_REQUEST";
export const STORE_PRODUCTS_UPDATE_SUCCESS = "STORE_PRODUCTS_UPDATE_SUCCESS";
export const STORE_PRODUCTS_UPDATE_FAIL = "STORE_PRODUCTS_UPDATE_FAIL";
export const STORE_PRODUCTS_UPDATE_RESET = "STORE_PRODUCTS_UPDATE_RESET";

export const STORE_PRODUCTS_DELETE_REQUEST = "STORE_PRODUCTS_DELETE_REQUEST";
export const STORE_PRODUCTS_DELETE_SUCCESS = "STORE_PRODUCTS_DELETE_SUCCESS";
export const STORE_PRODUCTS_DELETE_FAIL = "STORE_PRODUCTS_DELETE_FAIL";
export const STORE_PRODUCTS_DELETE_RESET = "STORE_PRODUCTS_DELETE_RESET";

export const ADMIN_STORE_PRODUCTS_REQUEST = "ADMIN_STORE_PRODUCTS_REQUEST";
export const ADMIN_STORE_PRODUCTS_SUCCESS = "ADMIN_STORE_PRODUCTS_SUCCESS";
export const ADMIN_STORE_PRODUCTS_FAIL = "ADMIN_STORE_PRODUCTS_FAIL";

export const NEW_STORE_PRODUCTS_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_STORE_PRODUCTS_SUCCESS = "NEW_STORE_PRODUCTS_SUCCESS";
export const NEW_STORE_PRODUCTS_RESET = "NEW_STORE_PRODUCTS_RESET";
export const NEW_STORE_PRODUCTS_FAIL = "NEW_STORE_PRODUCTS_FAIL";

export const STORE_PRODUCTS_DETAILS_REQUEST = "STORE_PRODUCTS_DETAILS_REQUEST";
export const STORE_PRODUCTS_DETAILS_SUCCESS = "STORE_PRODUCTS_DETAILS_SUCCESS";
export const STORE_PRODUCTS_DETAILS_FAIL = "STORE_PRODUCTS_DETAILS_FAIL";

export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_RESET = "NEW_ORDER_RESET";
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const NEW_CUSTOMER_REQUEST = "NEW_CUSTOMER_REQUEST";
export const NEW_CUSTOMER_SUCCESS = "NEW_CUSTOMER_SUCCESS";
export const NEW_CUSTOMER_RESET = "NEW_CUSTOMER_RESET";
export const NEW_CUSTOMER_FAIL = "NEW_CUSTOMER_FAIL";

export const ALL_CUSTOMERS_REQUEST = "ALL_CUSTOMERS_REQUEST";
export const ALL_CUSTOMERS_SUCCESS = "ALL_CUSTOMERS_SUCCESS";
export const ALL_CUSTOMERS_FAIL = "ALL_CUSTOMERS_FAIL";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_RESET = "DELETE_CUSTOMER_RESET";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEWS_REQUEST = "ALL_REVIEWS_REQUEST";
export const ALL_REVIEWS_SUCCESS = "ALL_REVIEWS_SUCCESS";
export const ALL_REVIEWS_FAIL = "ALL_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
