export const SIGNED_UP_USER_LOGIN_REQUEST = "SIGNED_UP_USER_LOGIN_REQUEST";
export const SIGNED_UP_USER_LOGIN_SUCCESS = "SIGNED_UP_USER_LOGIN_SUCCESS";
export const SIGNED_UP_USER_LOGIN_FAIL = "SIGNED_UP_USER_LOGIN_FAIL";
export const SIGNED_UP_USER_LOGOUT = "SIGNED_UP_USER_LOGOUT";

export const USER_SIGN_UP_REQUEST = "USER_SIGN_UP_REQUEST";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_UP_FAIL = "USER_SIGN_UP_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_RESET = "UPDATE_USER_PASSWORD_RESET";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";

export const FORGOT_USER_PASSWORD_REQUEST = "FORGOT_USER_PASSWORD_REQUEST";
export const FORGOT_USER_PASSWORD_SUCCESS = "FORGOT_USER_PASSWORD_SUCCESS";
export const FORGOT_USER_PASSWORD_FAIL = "FORGOT_USER_PASSWORD_FAIL";

export const RESET_USER_PASSWORD_REQUEST = "RESET_USER_PASSWORD_REQUEST";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAIL = "RESET_USER_PASSWORD_FAIL";

export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const NEW_ORDERED_FROM_REQUEST = "NEW_ORDERED_FROM_REQUEST";
export const NEW_ORDERED_FROM_SUCCESS = "NEW_ORDERED_FROM_SUCCESS";
export const NEW_ORDERED_FROM_RESET = "NEW_ORDERED_FROM_RESET";
export const NEW_ORDERED_FROM_FAIL = "NEW_ORDERED_FROM_FAIL";

export const ALL_ORDERED_FROM_REQUEST = "ALL_ORDERED_FROM_REQUEST";
export const ALL_ORDERED_FROM_SUCCESS = "ALL_ORDERED_FROM_SUCCESS";
export const ALL_ORDERED_FROM_FAIL = "ALL_ORDERED_FROM_FAIL";

export const DELETE_ORDERED_FROM_REQUEST = "DELETE_ORDERED_FROM_REQUEST";
export const DELETE_ORDERED_FROM_SUCCESS = "DELETE_ORDERED_FROM_SUCCESS";
export const DELETE_ORDERED_FROM_RESET = "DELETE_ORDERED_FROM_RESET";
export const DELETE_ORDERED_FROM_FAIL = "DELETE_ORDERED_FROM_FAIL";

export const NEW_CAMPAIGN_INVESTED_REQUEST = "NEW_CAMPAIGN_INVESTED_REQUEST";
export const NEW_CAMPAIGN_INVESTED_SUCCESS = "NEW_CAMPAIGN_INVESTED_SUCCESS";
export const NEW_CAMPAIGN_INVESTED_RESET = "NEW_CAMPAIGN_INVESTED_RESET";
export const NEW_CAMPAIGN_INVESTED_FAIL = "NEW_CAMPAIGN_INVESTED_FAIL";

export const NEW_CAMPAIGN_PAYOUT_REQUEST = "NEW_CAMPAIGN_PAYOUT_REQUEST";
export const NEW_CAMPAIGN_PAYOUT_SUCCESS = "NEW_CAMPAIGN_PAYOUT_SUCCESS";
export const NEW_CAMPAIGN_PAYOUT_RESET = "NEW_CAMPAIGN_PAYOUT_RESET";
export const NEW_CAMPAIGN_PAYOUT_FAIL = "NEW_CAMPAIGN_PAYOUT_FAIL";

export const ALL_CAMPAIGNS_INVESTED_REQUEST = "ALL_CAMPAIGNS_INVESTED_REQUEST";
export const ALL_CAMPAIGNS_INVESTED_SUCCESS = "ALL_CAMPAIGNS_INVESTED_SUCCESS";
export const ALL_CAMPAIGNS_INVESTED_FAIL = "ALL_CAMPAIGNS_INVESTED_FAIL";

export const ALL_CAMPAIGNS_PAYOUT_REQUEST = "ALL_CAMPAIGNS_PAYOUT_REQUEST";
export const ALL_CAMPAIGNS_PAYOUT_SUCCESS = "ALL_CAMPAIGNS_PAYOUT_SUCCESS";
export const ALL_CAMPAIGNS_PAYOUT_FAIL = "ALL_CAMPAIGNS_PAYOUT_FAIL";

export const PARTICULAR_CAMPAIGNS_INVESTED_REQUEST =
  "PARTICULAR_CAMPAIGNS_INVESTED_REQUEST";
export const PARTICULAR_CAMPAIGNS_INVESTED_SUCCESS =
  "PARTICULAR_CAMPAIGNS_INVESTED_SUCCESS";
export const PARTICULAR_CAMPAIGNS_INVESTED_FAIL =
  "PARTICULAR_CAMPAIGNS_INVESTED_FAIL";
export const PARTICULAR_CAMPAIGNS_PAYOUT_REQUEST =
  "PARTICULAR_CAMPAIGNS_PAYOUT_REQUEST";
export const PARTICULAR_CAMPAIGNS_PAYOUT_SUCCESS =
  "PARTICULAR_CAMPAIGNS_PAYOUT_SUCCESS";
export const PARTICULAR_CAMPAIGNS_PAYOUT_FAIL =
  "PARTICULAR_CAMPAIGNS_PAYOUT_FAIL";

export const DELETE_CAMPAIGN_INVESTED_REQUEST =
  "DELETE_CAMPAIGN_INVESTED_REQUEST";
export const DELETE_CAMPAIGN_INVESTED_SUCCESS =
  "DELETE_CAMPAIGN_INVESTED_SUCCESS";
export const DELETE_CAMPAIGN_INVESTED_RESET = "DELETE_CAMPAIGN_INVESTED_RESET";
export const DELETE_CAMPAIGN_INVESTED_FAIL = "DELETE_CAMPAIGN_INVESTED_FAIL";

export const DELETE_CAMPAIGN_PAYOUT_REQUEST = "DELETE_CAMPAIGN_PAYOUT_REQUEST";
export const DELETE_CAMPAIGN_PAYOUT_SUCCESS = "DELETE_CAMPAIGN_PAYOUT_SUCCESS";
export const DELETE_CAMPAIGN_PAYOUT_RESET = "DELETE_CAMPAIGN_PAYOUT_RESET";
export const DELETE_CAMPAIGN_PAYOUT_FAIL = "DELETE_CAMPAIGN_PAYOUT_FAIL";

export const NEW_CAMPAIGN_REVIEWS_REQUEST = "NEW_CAMPAIGN_REVIEWS_REQUEST";
export const NEW_CAMPAIGN_REVIEWS_SUCCESS = "NEW_CAMPAIGN_REVIEWS_SUCCESS";
export const NEW_CAMPAIGN_REVIEWS_RESET = "NEW_CAMPAIGN_REVIEWS_RESET";
export const NEW_CAMPAIGN_REVIEWS_FAIL = "NEW_CAMPAIGN_REVIEWS_FAIL";

export const ALL_CAMPAIGNS_REVIEWS_REQUEST = "ALL_CAMPAIGNS_REVIEWS_REQUEST";
export const ALL_CAMPAIGNS_REVIEWS_SUCCESS = "ALL_CAMPAIGNS_REVIEWS_SUCCESS";
export const ALL_CAMPAIGNS_REVIEWS_FAIL = "ALL_CAMPAIGNS_REVIEWS_FAIL";

export const DELETE_CAMPAIGN_REVIEWS_REQUEST =
  "DELETE_CAMPAIGN_REVIEWS_REQUEST";
export const DELETE_CAMPAIGN_REVIEWS_SUCCESS =
  "DELETE_CAMPAIGN_REVIEWS_SUCCESS";
export const DELETE_CAMPAIGN_REVIEWS_RESET = "DELETE_CAMPAIGN_REVIEWS_RESET";
export const DELETE_CAMPAIGN_REVIEWS_FAIL = "DELETE_CAMPAIGN_REVIEWS_FAIL";

export const NEW_PRODUCT_REVIEWS_REQUEST = "NEW_PRODUCT_REVIEWS_REQUEST";
export const NEW_PRODUCT_REVIEWS_SUCCESS = "NEW_PRODUCT_REVIEWS_SUCCESS";
export const NEW_PRODUCT_REVIEWS_RESET = "NEW_PRODUCT_REVIEWS_RESET";
export const NEW_PRODUCT_REVIEWS_FAIL = "NEW_PRODUCT_REVIEWS_FAIL";

export const ALL_PRODUCTS_REVIEWS_REQUEST = "ALL_PRODUCTS_REVIEWS_REQUEST";
export const ALL_PRODUCTS_REVIEWS_SUCCESS = "ALL_PRODUCTS_REVIEWS_SUCCESS";
export const ALL_PRODUCTS_REVIEWS_FAIL = "ALL_PRODUCTS_REVIEWS_FAIL";

export const DELETE_PRODUCT_REVIEWS_REQUEST = "DELETE_PRODUCT_REVIEWS_REQUEST";
export const DELETE_PRODUCT_REVIEWS_SUCCESS = "DELETE_PRODUCT_REVIEWS_SUCCESS";
export const DELETE_PRODUCT_REVIEWS_RESET = "DELETE_PRODUCT_REVIEWS_RESET";
export const DELETE_PRODUCT_REVIEWS_FAIL = "DELETE_PRODUCT_REVIEWS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
